# Generated by Django 4.2.16 on 2026-04-20 19:52

import aos.models
from django.db import migrations, models
import stages.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('aopdf', models.FileField(upload_to=aos.models.rename_upload_path_ao, validators=[stages.validators.validate_file_extension])),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(default=aos.models.default_expiration_date)),
            ],
            options={
                'permissions': [('can_download', 'Can download ao data')],
            },
        ),
    ]
