# Generated by Django 3.2.25 on 2025-08-04 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 25, 0, 2, 31, 667316, tzinfo=utc)),
        ),
    ]
