# Generated by Django 3.2.25 on 2025-08-04 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0002_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 25, 17, 35, 34, 958146, tzinfo=utc)),
        ),
    ]
