# Generated by Django 3.2.25 on 2025-08-29 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0003_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 19, 15, 23, 45, 638476, tzinfo=utc)),
        ),
    ]
