# Generated by Django 3.2.25 on 2025-08-30 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0005_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 20, 0, 7, 16, 63455, tzinfo=utc)),
        ),
    ]
