# Generated by Django 3.2.25 on 2025-09-30 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0006_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 21, 15, 59, 55, 349012, tzinfo=utc)),
        ),
    ]
