# Generated by Django 3.2.25 on 2025-09-16 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0007_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 7, 22, 24, 25, 997344, tzinfo=utc)),
        ),
    ]
