# Generated by Django 3.2.25 on 2025-09-20 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0008_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 11, 17, 27, 52, 209159, tzinfo=utc)),
        ),
    ]
