# Generated by Django 3.2.25 on 2025-10-16 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0009_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 6, 9, 2, 16, 49680, tzinfo=utc)),
        ),
    ]
