# Generated by Django 3.2.25 on 2025-10-27 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0010_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 17, 21, 57, 25, 285859, tzinfo=utc)),
        ),
    ]
