# Generated by Django 3.2.25 on 2025-11-08 23:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0011_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 29, 23, 28, 55, 68490, tzinfo=utc)),
        ),
    ]
