# Generated by Django 4.2.16 on 2025-11-12 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0012_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 3, 21, 43, 15, 102664, tzinfo=datetime.timezone.utc)),
        ),
    ]
