# Generated by Django 4.2.16 on 2026-04-11 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0014_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 2, 23, 4, 11, 562389, tzinfo=datetime.timezone.utc)),
        ),
    ]
