# Generated by Django 4.2.16 on 2026-04-12 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0016_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 3, 14, 45, 1, 510116, tzinfo=datetime.timezone.utc)),
        ),
    ]
