# Generated by Django 4.2.16 on 2026-04-12 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0018_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 3, 16, 8, 52, 303069, tzinfo=datetime.timezone.utc)),
        ),
    ]
