# Generated by Django 4.2.16 on 2026-04-13 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aos', '0019_alter_ao_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 4, 7, 23, 56, 791959, tzinfo=datetime.timezone.utc)),
        ),
    ]
