# Generated by Django 3.2.25 on 2025-01-01 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(help_text='Nom ou raison sociale du bénéficiaire', max_length=32, verbose_name='Raison Sociale')),
                ('guichet', models.CharField(help_text='Libellé du guichet associé. Exemples : BMCE, BP, ATW, ...', max_length=16, verbose_name='Guichet')),
                ('rib', models.CharField(help_text='Numéro du compte bancaire', max_length=24, validators=[django.core.validators.RegexValidator(message='Le RIB doit contenir uniquement des chiffres.', regex='^\\d+$')], verbose_name='RIB')),
            ],
        ),
        migrations.CreateModel(
            name='OrdreVirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant du virement (max 10 chiffres, 2 décimales)', max_digits=10, verbose_name='Montant')),
                ('facture', models.CharField(help_text='Référence de la facture', max_length=32, verbose_name='Facture')),
                ('date', models.DateField(auto_now_add=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_beneficiaire', to='ovs.beneficiaire')),
                ('guichet_interne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_guichet', to='ovs.beneficiaire')),
            ],
        ),
    ]
