# Generated by Django 3.2.25 on 2025-01-01 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='guichet',
            field=models.CharField(help_text='Libellé du guichet associé. Exemples : BMCE, BP, ATW, ...', max_length=20, verbose_name='Guichet'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='raison_sociale',
            field=models.CharField(help_text='Nom ou raison sociale du bénéficiaire', max_length=50, verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='rib',
            field=models.CharField(help_text='Numéro du compte bancaire', max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Le RIB doit contenir uniquement des chiffres.', regex='^\\d+$')], verbose_name='RIB'),
        ),
        migrations.AddConstraint(
            model_name='ordrevirement',
            constraint=models.UniqueConstraint(fields=('facture', 'beneficiaire'), name='unique_facture_beneficiaire'),
        ),
    ]
