# Generated by Django 3.2.25 on 2025-01-01 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0002_auto_20250101_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='rib',
            field=models.CharField(help_text='Numéro du compte bancaire', max_length=24, validators=[django.core.validators.RegexValidator(message='Le RIB doit contenir uniquement des chiffres.', regex='^\\d+$')], verbose_name='RIB'),
        ),
    ]
