# Generated by Django 3.2.25 on 2025-01-03 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0003_alter_beneficiaire_rib'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(help_text='Nom de la banque', max_length=50, verbose_name='Banque')),
                ('rib', models.CharField(help_text='Numéro du compte bancaire', max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Le RIB doit contenir uniquement des chiffres.', regex='^\\d+$')], verbose_name='RIB')),
                ('attestation_rib_pdf', models.FileField(blank=True, help_text="Fichier PDF de l'attestation RIB", null=True, upload_to='attestations_rib/', verbose_name='Attestation RIB PDF')),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiaire',
            name='guichet',
        ),
        migrations.RemoveField(
            model_name='beneficiaire',
            name='rib',
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='code_ice',
            field=models.CharField(default='', help_text="Identifiant Commun de l'Entreprise (ICE)", max_length=15, verbose_name='Code ICE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='identifiant_fiscale',
            field=models.CharField(default='', help_text='Identifiant fiscal du bénéficiaire', max_length=20, verbose_name='Identifiant Fiscale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='registre_commerce',
            field=models.CharField(default='', help_text='Numéro de registre du commerce', max_length=20, verbose_name='Registre du Commerce'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrdreVirement',
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_bancaires', to='ovs.beneficiaire', verbose_name='Bénéficiaire'),
        ),
    ]
