# Generated by Django 3.2.25 on 2025-01-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0005_auto_20250103_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='mnt_net_apayer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant net à payer'),
        ),
    ]
