# Generated by Django 3.2.25 on 2025-01-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0006_alter_facture_mnt_net_apayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='PV_reception_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la reception', null=True, upload_to='receptions/', verbose_name='Reception PDF'),
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la facture', null=True, upload_to='factures/', verbose_name='Facture PDF'),
        ),
        migrations.AddField(
            model_name='ordrevirement',
            name='OV_signe_pdf',
            field=models.FileField(blank=True, help_text="Fichier PDF de l'OV", null=True, upload_to='virements/', verbose_name='OV signe PDF'),
        ),
    ]
