# Generated by Django 3.2.25 on 2025-02-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0007_auto_20250106_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='ordre_virement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_ov', to='ovs.ordrevirement', verbose_name='Ordre de virement'),
        ),
    ]
