# Generated by Django 4.2.16 on 2026-04-22 07:42

from django.db import migrations, models
import stages10.models


class Migration(migrations.Migration):

    dependencies = [
        ('stages10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='cin',
            field=models.CharField(default='Z5454545', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(upload_to=stages10.models.rename_upload_path_cv),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='lettre',
            field=models.FileField(upload_to=stages10.models.rename_upload_path_lettre),
        ),
    ]
