# Generated by Django 4.2.16 on 2026-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages10', '0002_candidat_cin_alter_candidature_cv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidature',
            options={'ordering': ['-date_soumission'], 'verbose_name': 'Candidature', 'verbose_name_plural': 'Candidatures'},
        ),
        migrations.AddField(
            model_name='candidature',
            name='commentaire_interne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('RECUE', 'Reçue'), ('EXAMEN', "En cours d'examen"), ('ENTRETIEN', 'Entretien planifié'), ('OFFRE', 'Offre envoyée'), ('RETENUE', 'Retenue (Recruté)'), ('REFUSEE', 'Non retenue')], default='RECUE', max_length=20),
        ),
    ]
