# Generated by Django 3.2.25 on 2025-03-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationDiverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('date_operation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EcritureOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type_operation', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=6)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationsDiverses.compte')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='operationsDiverses.operationdiverse')),
            ],
        ),
    ]
