# Generated by Django 3.2.25 on 2025-04-14 11:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationDiverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField(max_length=255)),
                ('date_operation', models.DateField(auto_now_add=True)),
                ('annee_comptable', models.IntegerField(default=2025)),
                ('justif_pdf', models.FileField(blank=True, null=True, upload_to='operationsDiverses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EcritureOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sens_ecriture', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=6)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operationsDiverses.compte')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='operationsDiverses.operationdiverse')),
            ],
        ),
    ]
