# Generated by Django 4.2.16 on 2026-04-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsDiverses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdiverse',
            name='annee_comptable',
            field=models.IntegerField(default=2026),
        ),
    ]
