# Generated by Django 3.2.25 on 2025-03-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsDiverses', '0003_operationdiverse_annee_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdiverse',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
