# Generated by Django 3.2.25 on 2025-03-14 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsDiverses', '0005_auto_20250314_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationdiverse',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='operationdiverse',
            name='total_debit',
        ),
        migrations.AlterField(
            model_name='operationdiverse',
            name='annee_comptable',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='operationdiverse',
            name='justif_pdf',
            field=models.FileField(blank=True, null=True, upload_to='operationsDiverses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
