# Generated by Django 3.2.25 on 2025-03-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsDiverses', '0006_auto_20250314_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdiverse',
            name='libelle',
            field=models.TextField(max_length=255),
        ),
    ]
