# Generated by Django 4.2.16 on 2026-04-11 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0014_alter_ordrevirement_ov_remis_banque_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_client_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_client_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date_signature', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement'), ('cheque', 'Chèque')], max_length=10)),
                ('taux_ras_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_ras_is', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scan_pdf', models.FileField(blank=True, help_text='Scan du contrat (PDF)', null=True, upload_to='contrats/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='clients.client')),
                ('compte_bancaire', models.ForeignKey(blank=True, limit_choices_to={'beneficiaire__raison_sociale': 'Supratours Travel', 'type_compte': 'bancaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_encaissement', to='fournisseurs.comptetresorerie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_contrat_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avenants', to='clients.contrat')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_contrat_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_encaissement', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='clients.client')),
                ('compte_bancaire', models.ForeignKey(limit_choices_to={'beneficiaire__raison_sociale': 'Supratours Travel', 'type_compte': 'bancaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaissement', to='fournisseurs.comptetresorerie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_paiement_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_paiement_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_ras_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_ras_is', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scan_pdf', models.FileField(blank=True, help_text='Scan de la facture (PDF)', null=True, upload_to='factures/')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.contrat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_facture_created_by', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.paiement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_facture_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
