# Generated by Django 4.2.16 on 2026-04-11 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='entite_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='is_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='is_solde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='taux_ras_tva',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='contrat',
            field=models.ForeignKey(limit_choices_to={'is_actif': True, 'is_solde': False}, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.contrat'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='paiement',
            field=models.ForeignKey(blank=True, limit_choices_to={'est_solde': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
