# Generated by Django 4.2.16 on 2026-04-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_contrat_entite_client_contrat_is_actif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant_ht',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='taux_ras_is',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='taux_ras_tva',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='taux_tva',
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_tva', models.DecimalField(decimal_places=2, help_text='Montant sur lequel la TVA est appliquée', max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_ras_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_ras_is', models.DecimalField(decimal_places=2, max_digits=5)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='clients.facture')),
            ],
        ),
    ]
