# Generated by Django 4.2.16 on 2026-04-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_facture_montant_ht_remove_facture_taux_ras_is_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='scan_pdf',
            field=models.FileField(blank=True, help_text='Scan du contrat (PDF)', null=True, upload_to='clients/contrats/'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.paiement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='scan_pdf',
            field=models.FileField(blank=True, help_text='Scan de la facture (PDF)', null=True, upload_to='clients/factures/'),
        ),
    ]
