# Generated by Django 4.2.16 on 2026-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_contrat_scan_pdf_alter_facture_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(default='FS26000001', max_length=10, unique=True, verbose_name='Numéro de facture'),
            preserve_default=False,
        ),
    ]
