# Generated by Django 4.2.16 on 2026-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_facture_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_cpt',
            field=models.CharField(default='34210517', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
