# Generated by Django 4.2.16 on 2026-04-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_id_cpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='partie_liee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_accord_ca',
            field=models.DateField(blank=True, help_text="Date de l'accord du Conseil d'Administration pour les parties liées", null=True),
        ),
    ]
