# Generated by Django 4.2.16 on 2026-04-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_partie_liee_contrat_date_accord_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('autorise', 'Autorisé'), ('non_valide', 'Non encore validé')], default='non_valide', max_length=20),
        ),
    ]
