# Generated by Django 3.2.25 on 2025-02-12 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(help_text='Nom ou raison sociale du bénéficiaire', max_length=50, unique=True, verbose_name='Raison sociale')),
                ('registre_commerce', models.CharField(help_text='Numéro de registre du commerce', max_length=20, unique=True, verbose_name='Registre du commerce')),
                ('identifiant_fiscale', models.CharField(help_text='Identifiant fiscal du bénéficiaire', max_length=20, unique=True, verbose_name='Identifiant fiscal')),
                ('code_ice', models.CharField(help_text="Identifiant Commun de l'Entreprise (ICE)", max_length=15, unique=True, verbose_name='Code ICE')),
            ],
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(help_text='Nom de la banque', max_length=50, verbose_name='Banque')),
                ('rib', models.CharField(help_text='Numéro du compte bancaire', max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Le RIB doit contenir exactement 24 chiffres.', regex='^\\d{24}$')], verbose_name='RIB')),
                ('attestation_rib_pdf', models.FileField(blank=True, help_text="Fichier PDF de l'attestation RIB", null=True, upload_to='attestations_rib/', verbose_name='Attestation RIB PDF')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_bancaires', to='fournisseurs.beneficiaire', verbose_name='Bénéficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=20, unique=True, verbose_name='Numéro de contrat')),
                ('objet', models.CharField(max_length=100, verbose_name='Objet')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('montant_TTC', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant TTC')),
                ('taux_RAS_TVA', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux RAS TVA')),
                ('taux_RAS_IS', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux RAS IS')),
                ('taux_RG', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux RG')),
                ('contrat_pdf', models.FileField(blank=True, help_text='Fichier PDF du contrat', null=True, upload_to='contrats/', verbose_name='Contrat PDF')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='fournisseurs.beneficiaire', verbose_name='Bénéficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='OrdreVirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ov', models.CharField(choices=[('Virement', 'Virement'), ('Transfert', 'Transfert')], max_length=15, verbose_name="Type d'ordre de virement")),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('date_ov', models.DateField(auto_now_add=True, verbose_name="Date de l'ordre de virement")),
                ('valide_pour_signature', models.BooleanField(default=False)),
                ('valide_pour_paiement', models.BooleanField(default=False)),
                ('OV_signe_pdf', models.FileField(blank=True, help_text="Fichier PDF de l'OV", null=True, upload_to='virements/', verbose_name='OV signe PDF')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_virements', to='fournisseurs.beneficiaire', verbose_name='Bénéficiaire')),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_virements_compte', to='fournisseurs.comptebancaire', verbose_name='Compte bancaire')),
                ('compte_bancaire_emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_virements_emetteur', to='fournisseurs.comptebancaire', verbose_name='Compte bancaire émetteur')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TVA')),
                ('mnt_RAS_TVA', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant RAS TVA')),
                ('mnt_RAS_IS', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant RAS IS')),
                ('mnt_RG', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant RG')),
                ('mnt_net_apayer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant net à payer')),
                ('facture_pdf', models.FileField(blank=True, help_text='Fichier PDF de la facture', null=True, upload_to='factures/', verbose_name='Facture PDF')),
                ('PV_reception_pdf', models.FileField(blank=True, help_text='Fichier PDF de la reception', null=True, upload_to='receptions/', verbose_name='Reception PDF')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_beneficiaire', to='fournisseurs.beneficiaire', verbose_name='Bénéficiaire')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures_contrat', to='fournisseurs.contrat', verbose_name='Contrat')),
                ('ordre_virement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_ov', to='fournisseurs.ordrevirement', verbose_name='Ordre de virement')),
            ],
        ),
    ]
