# Generated by Django 3.2.25 on 2025-04-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='type_achat',
            field=models.CharField(choices=[('fournitures', 'Fournitures'), ('prestations', 'Prestations'), ('equip_travaux', 'Equipement et Travaux')], default='prestations', max_length=30, verbose_name='Type achat'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_achat',
            field=models.CharField(choices=[('fournitures', 'Fournitures'), ('prestations', 'Prestations'), ('equip_travaux', 'Equipement et Travaux')], default='prestations', max_length=30, verbose_name='Type achat'),
        ),
    ]
