# Generated by Django 3.2.25 on 2025-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_auto_20250420_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoir',
            name='type_achat',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='type_achat',
        ),
        migrations.AddField(
            model_name='avoir',
            name='nature_achat',
            field=models.CharField(choices=[('fournitures', 'Fournitures'), ('prestations', 'Prestations'), ('equip_travaux', 'Equipement et Travaux')], default='prestations', max_length=30, verbose_name='Nature achat'),
        ),
        migrations.AddField(
            model_name='facture',
            name='nature_achat',
            field=models.CharField(choices=[('fournitures', 'Fournitures'), ('prestations', 'Prestations'), ('equip_travaux', 'Equipement et Travaux')], default='prestations', max_length=30, verbose_name='Nature achat'),
        ),
    ]
