# Generated by Django 3.2.25 on 2025-02-13 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_auto_20250213_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='code_ice',
            field=models.CharField(error_messages={'unique': 'Ce code ICE est déjà utilisé.'}, help_text="Identifiant Commun de l'Entreprise (ICE)", max_length=15, unique=True, verbose_name='Code ICE'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='identifiant_fiscale',
            field=models.CharField(error_messages={'unique': 'Cet identifiant fiscal est déjà utilisé.'}, help_text='Identifiant fiscal du bénéficiaire', max_length=20, unique=True, verbose_name='Identifiant fiscal'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='raison_sociale',
            field=models.CharField(error_messages={'unique': 'Cette raison sociale est déjà utilisée.'}, help_text='Nom ou raison sociale du bénéficiaire', max_length=50, unique=True, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='registre_commerce',
            field=models.CharField(error_messages={'unique': 'Ce registre du commerce est déjà utilisé.'}, help_text='Numéro de registre du commerce', max_length=20, unique=True, verbose_name='Registre du commerce'),
        ),
        migrations.AlterField(
            model_name='comptebancaire',
            name='attestation_rib_pdf',
            field=models.FileField(blank=True, help_text="Fichier PDF de l'attestation RIB", null=True, upload_to='attestations_rib/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Attestation RIB PDF'),
        ),
        migrations.AlterField(
            model_name='comptebancaire',
            name='rib',
            field=models.CharField(error_messages={'unique': 'Ce RIB est déjà utilisé.'}, help_text='Numéro du compte bancaire', max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Le RIB doit contenir exactement 24 chiffres.', regex='^\\d{24}$')], verbose_name='RIB'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='contrat_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF du contrat', null=True, upload_to='contrats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Contrat PDF'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='numero_contrat',
            field=models.CharField(error_messages={'unique': 'Ce numéro de contrat est déjà utilisé.'}, max_length=20, unique=True, verbose_name='Numéro de contrat'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='PV_reception_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la reception', null=True, upload_to='receptions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Reception PDF'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la facture', null=True, upload_to='factures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Facture PDF'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='proforma_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF de la facture proforma', null=True, upload_to='proformas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Proforma PDF'),
        ),
        migrations.AlterField(
            model_name='ordrevirement',
            name='OV_remis_banque_pdf',
            field=models.FileField(blank=True, help_text="Fichier PDF de l'OV avec AR banque", null=True, upload_to='virements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='OV signe PDF'),
        ),
    ]
