# Generated by Django 3.2.25 on 2025-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_auto_20250420_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='nature_achat',
            field=models.CharField(choices=[('prestations', 'Achat de services'), ('travaux', 'Achat de travaux'), ('equipement', "Achat de biens d'équipement"), ('fournitures', 'Achat de fournitures')], default='prestations', max_length=30, verbose_name='Nature achat'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='nature_achat',
            field=models.CharField(choices=[('prestations', 'Achat de services'), ('travaux', 'Achat de travaux'), ('equipement', "Achat de biens d'équipement"), ('fournitures', 'Achat de fournitures')], default='prestations', max_length=30, verbose_name='Nature achat'),
        ),
    ]
