# Generated by Django 3.2.25 on 2025-02-14 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_auto_20250213_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrevirement',
            name='date_operation_banque',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date opération sur relevé bancaire'),
        ),
        migrations.AddField(
            model_name='ordrevirement',
            name='date_remise_banque',
            field=models.DateField(default='2025-02-14', verbose_name="Date remise de l'ordre de virement à la banque"),
            preserve_default=False,
        ),
    ]
