# Generated by Django 3.2.25 on 2025-06-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0004_auto_20250425_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_execution',
            field=models.DateField(blank=True, null=True, verbose_name="Date de base de calcul de l'échéance"),
        ),
    ]
