# Generated by Django 3.2.25 on 2025-02-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0004_auto_20250214_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordrevirement',
            name='date_operation_banque',
            field=models.DateField(verbose_name='Date opération sur relevé bancaire'),
        ),
    ]
