# Generated by Django 3.2.25 on 2025-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0005_alter_ordrevirement_date_operation_banque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordrevirement',
            name='date_operation_banque',
            field=models.DateField(blank=True, null=True, verbose_name='Date opération sur relevé bancaire'),
        ),
        migrations.AlterField(
            model_name='ordrevirement',
            name='date_remise_banque',
            field=models.DateField(blank=True, null=True, verbose_name="Date remise de l'ordre de virement à la banque"),
        ),
    ]
