# Generated by Django 3.2.25 on 2025-06-27 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0005_alter_facture_date_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='mnt_avoir',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant Avoir'),
        ),
        migrations.AddField(
            model_name='avoir',
            name='mnt_penalite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant Pénalité'),
        ),
        migrations.AddField(
            model_name='facture',
            name='avoir_pdf',
            field=models.FileField(blank=True, help_text="Fichier PDF de l'avoir", null=True, upload_to='avoirs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Avoir PDF'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mnt_avoir',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant Avoir'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mnt_penalite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant Pénalité'),
        ),
    ]
