# Generated by Django 3.2.25 on 2025-02-16 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0006_auto_20250214_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(choices=[('bancaire', 'Compte bancaire'), ('caisse', 'Caisse')], default='bancaire', help_text='Type de compte (bancaire ou caisse)', max_length=10, verbose_name='Type de compte')),
                ('banque', models.CharField(blank=True, help_text='Nom de la banque (uniquement pour les comptes bancaires)', max_length=50, null=True, verbose_name='Banque')),
                ('rib', models.CharField(blank=True, error_messages={'unique': 'Ce RIB est déjà utilisé.'}, help_text='Numéro du compte bancaire (uniquement pour les comptes bancaires)', max_length=24, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le RIB doit contenir exactement 24 chiffres.', regex='^\\d{24}$')], verbose_name='RIB')),
                ('attestation_rib_pdf', models.FileField(blank=True, help_text="Fichier PDF de l'attestation RIB (uniquement pour les comptes bancaires)", null=True, upload_to='attestations_rib/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Attestation RIB PDF')),
                ('nom_caisse', models.CharField(blank=True, help_text='Nom de la caisse (uniquement pour les caisses)', max_length=50, null=True, verbose_name='Nom de la caisse')),
                ('emplacement_caisse', models.CharField(blank=True, help_text='Emplacement physique de la caisse (uniquement pour les caisses)', max_length=100, null=True, verbose_name='Emplacement de la caisse')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='fournisseurs.beneficiaire', verbose_name='Bénéficiaire')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordrevirement',
            name='compte_bancaire',
        ),
        migrations.RemoveField(
            model_name='ordrevirement',
            name='compte_bancaire_emetteur',
        ),
        migrations.DeleteModel(
            name='CompteBancaire',
        ),
        migrations.AddField(
            model_name='ordrevirement',
            name='compte_tresorerie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordres_virements_compte', to='fournisseurs.comptetresorerie', verbose_name='Compte bancaire'),
        ),
        migrations.AddField(
            model_name='ordrevirement',
            name='compte_tresorerie_emetteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordres_virements_emetteur', to='fournisseurs.comptetresorerie', verbose_name='Compte bancaire émetteur'),
        ),
    ]
