# Generated by Django 3.2.25 on 2025-07-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0006_auto_20250627_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avoir',
        ),
    ]
