# Generated by Django 3.2.25 on 2025-02-17 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0007_auto_20250216_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='montant_TTC',
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_HT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant HT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='taux_de_TVA',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Taux de TVA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='date_execution',
            field=models.DateField(default='2025-02-15', verbose_name="Date d'exécution ou de réception"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordrevirement',
            name='avis_debit_pdf',
            field=models.FileField(blank=True, help_text='Avis de débit', null=True, upload_to='avisDebit/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='avis de débit PDF'),
        ),
        migrations.AddField(
            model_name='ordrevirement',
            name='compte_debite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='fournisseurs.beneficiaire', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='taux_RAS_IS',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Taux RAS IS'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='taux_RG',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Taux RG'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures_contrat', to='fournisseurs.contrat', verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('etablissement', "OV en cours d'établissement"), ('signature', 'OV en cours de signature'), ('banque', 'OV remis à la banque'), ('payee', 'Facture payée')], default='attente', max_length=30, verbose_name='Statut de la facture'),
        ),
        migrations.AlterField(
            model_name='ordrevirement',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_virements', to='fournisseurs.beneficiaire', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='ordrevirement',
            name='compte_tresorerie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_virements_compte', to='fournisseurs.comptetresorerie', verbose_name='Compte bancaire'),
        ),
        migrations.AlterField(
            model_name='ordrevirement',
            name='compte_tresorerie_emetteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_virements_emetteur', to='fournisseurs.comptetresorerie', verbose_name='Compte bancaire émetteur'),
        ),
    ]
