# Generated by Django 3.2.25 on 2025-07-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0007_delete_avoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='mnt_avoir',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant Avoir HT'),
        ),
    ]
