# Generated by Django 3.2.25 on 2025-08-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0008_alter_facture_mnt_avoir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avoir',
        ),
    ]
