# Generated by Django 3.2.25 on 2025-02-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0008_auto_20250217_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_execution',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'exécution ou de réception"),
        ),
    ]
