# Generated by Django 3.2.25 on 2025-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0009_alter_facture_date_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrevirement',
            name='reference',
            field=models.CharField(default=1, max_length=15, verbose_name="Autre référence de l'ordre de virement si édité sur un autre système"),
            preserve_default=False,
        ),
    ]
