# Generated by Django 3.2.25 on 2025-09-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0009_delete_avoir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordrevirement',
            options={'ordering': ['beneficiaire__raison_sociale']},
        ),
    ]
