# Generated by Django 3.2.25 on 2025-10-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0010_alter_ordrevirement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordrevirement',
            options={},
        ),
    ]
