# Generated by Django 3.2.25 on 2025-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0011_auto_20250219_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='mode_paiement',
            field=models.CharField(choices=[('30J', '30 jours'), ('30JFDM', '30 jours fin de mois'), ('60J', '60 jours'), ('60JFDM', '60 jours fin de mois'), ('90J', '90 jours'), ('90JFDM', '90 jours fin de mois'), ('120J', '120 jours'), ('120JFDM', '120 jours fin de mois')], default='90JFDM', help_text='Mode de paiement', max_length=10, verbose_name='Mode de paiement'),
        ),
    ]
