# Generated by Django 3.2.25 on 2025-10-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0011_alter_ordrevirement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptetresorerie',
            name='banque',
            field=models.CharField(blank=True, help_text='Nom de la banque (uniquement pour les comptes bancaires ou chèque)', max_length=50, null=True, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='comptetresorerie',
            name='detenteur_caisse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Détenteur de la caisse'),
        ),
        migrations.AlterField(
            model_name='comptetresorerie',
            name='emplacement_caisse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emplacement de la caisse'),
        ),
        migrations.AlterField(
            model_name='comptetresorerie',
            name='nom_caisse',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la caisse'),
        ),
        migrations.AlterField(
            model_name='comptetresorerie',
            name='type_compte',
            field=models.CharField(choices=[('bancaire', 'Compte bancaire'), ('caisse', 'Caisse'), ('cheque', 'Paiement par chèque')], default='bancaire', help_text='Type de compte (bancaire, caisse ou chèque)', max_length=10, verbose_name='Type de compte'),
        ),
    ]
