# Generated by Django 3.2.25 on 2025-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0012_contrat_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_facture',
            field=models.DateField(default='2025-02-15', verbose_name='Date facture'),
            preserve_default=False,
        ),
    ]
