# Generated by Django 3.2.25 on 2025-02-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0013_facture_date_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='raison_sociale',
            field=models.CharField(error_messages={'unique': 'Cette raison sociale est déjà utilisée.'}, help_text='Nom ou raison sociale du bénéficiaire', max_length=100, unique=True, verbose_name='Raison sociale'),
        ),
    ]
