# Generated by Django 4.2.16 on 2026-04-11 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0013_alter_beneficiaire_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordrevirement',
            name='OV_remis_banque_pdf',
            field=models.FileField(blank=True, help_text="Fichier PDF de l'OV avec AR banque", null=True, upload_to='virements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='OV signé PDF'),
        ),
    ]
