# Generated by Django 3.2.25 on 2025-02-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0014_alter_beneficiaire_raison_sociale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiaire',
            options={'ordering': ['raison_sociale'], 'verbose_name': 'Bénéficiaire', 'verbose_name_plural': 'Bénéficiaires'},
        ),
        migrations.AddField(
            model_name='contrat',
            name='moe',
            field=models.CharField(choices=[('fm', 'Facility management'), ('services', 'Services'), ('tourisme', 'Tourisme'), ('cfo', 'Front office ONCF')], default='fm', help_text="Maitrise d'oeuvres", max_length=20, verbose_name="Maitrise d'oeuvres"),
        ),
    ]
