# Generated by Django 3.2.25 on 2025-02-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0015_auto_20250219_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('marche', 'Marché'), ('commande', 'Bon de commande'), ('contrat', 'Contrat')], default='marche', help_text='Type de contrat', max_length=20, verbose_name='Type de contrat'),
        ),
    ]
