# Generated by Django 3.2.25 on 2025-02-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0016_contrat_type_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='objet',
            field=models.CharField(max_length=500, verbose_name='Objet'),
        ),
    ]
