# Generated by Django 3.2.25 on 2025-02-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0017_alter_contrat_objet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='contrat_actif',
            field=models.BooleanField(default=True),
        ),
    ]
