# Generated by Django 3.2.25 on 2025-02-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0018_contrat_contrat_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptetresorerie',
            name='detenteur_caisse',
            field=models.CharField(blank=True, help_text='Détenteur de la caisse (uniquement pour les caisses)', max_length=100, null=True, verbose_name='Détenteur de la caisse'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='moe',
            field=models.CharField(choices=[('fm', 'Facility management'), ('services', 'Services'), ('tourisme', 'Tourisme'), ('cfo', 'Front office ONCF'), ('support', 'Support')], default='fm', help_text="Maitrise d'oeuvres", max_length=20, verbose_name="Maitrise d'oeuvres"),
        ),
    ]
