# Generated by Django 3.2.25 on 2025-02-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0019_auto_20250223_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date paiement'),
        ),
    ]
