# Generated by Django 3.2.25 on 2025-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0022_auto_20250226_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='num_facture',
            field=models.CharField(max_length=50, verbose_name='Numéro de facture'),
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.UniqueConstraint(fields=('beneficiaire', 'num_facture'), name='unique_beneficiaire_facture'),
        ),
    ]
