# Generated by Django 3.2.25 on 2025-02-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0023_auto_20250227_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptetresorerie',
            options={'ordering': ['beneficiaire']},
        ),
    ]
