# Generated by Django 3.2.25 on 2025-03-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0025_alter_contrat_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
