# Generated by Django 3.2.25 on 2025-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0026_alter_contrat_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TVA'),
        ),
    ]
