# Generated by Django 3.2.25 on 2025-03-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0027_auto_20250317_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='montant_tva',
            new_name='mnt_tva',
        ),
    ]
