# Generated by Django 3.2.25 on 2025-03-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0028_rename_montant_tva_facture_mnt_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrevirement',
            name='mode_execution',
            field=models.CharField(choices=[('INDIVIDUEL', 'Individuel'), ('MASSE', 'En masse')], default='INDIVIDUEL', max_length=20, verbose_name="Mode d'exécution"),
        ),
    ]
