# Generated by Django 3.2.25 on 2025-03-27 11:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fournisseurs', '0029_ordrevirement_mode_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant HT'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('etablissement', "OV en cours d'établissement"), ('signature', 'OV en cours de signature'), ('banque', 'OV remis à la banque'), ('payee', 'Facture payée')], default='attente', max_length=30, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_facture', models.CharField(max_length=50, verbose_name='Numéro de facture')),
                ('date_facture', models.DateField(verbose_name='Date facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('mnt_tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TTC')),
                ('mnt_RAS_TVA', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant RAS TVA')),
                ('mnt_RAS_IS', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant RAS IS')),
                ('mnt_RG', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant RG')),
                ('mnt_net_apayer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant net à payer')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date paiement')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('etablissement', "OV en cours d'établissement"), ('signature', 'OV en cours de signature'), ('banque', 'OV remis à la banque'), ('payee', 'Facture payée')], default='attente', max_length=30, verbose_name='Statut')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(-0.01)], verbose_name='Montant HT')),
                ('avoir_pdf', models.FileField(blank=True, help_text="Fichier PDF de l'avoir", null=True, upload_to='avoirs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Avoir PDF')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoir_created_by', to=settings.AUTH_USER_MODEL)),
                ('facture_associee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_avoirs', to='fournisseurs.facture', verbose_name='Facture associée')),
                ('ordre_virement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_ov', to='fournisseurs.ordrevirement', verbose_name='Ordre de virement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoir_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
