# Generated by Django 3.2.25 on 2025-03-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0030_auto_20250327_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='facture_associee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture_avoirs', to='fournisseurs.facture', verbose_name='Facture associée'),
        ),
    ]
