# Generated by Django 3.2.25 on 2025-03-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0031_alter_avoir_facture_associee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='facture_associee',
            field=models.ForeignKey(limit_choices_to={'statut': 'en_attente'}, on_delete=django.db.models.deletion.CASCADE, related_name='facture_avoirs', to='fournisseurs.facture', verbose_name='Facture associée'),
        ),
    ]
