# Generated by Django 3.2.25 on 2025-03-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0033_auto_20250331_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordrevirement',
            name='beneficiaire',
            field=models.ForeignKey(limit_choices_to={'actif': True}, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_virements', to='fournisseurs.beneficiaire', verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='ordrevirement',
            name='compte_tresorerie',
            field=models.ForeignKey(blank=True, limit_choices_to={'actif': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_virements_compte', to='fournisseurs.comptetresorerie', verbose_name='Compte bancaire'),
        ),
    ]
