# Generated by Django 3.2.25 on 2025-03-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0034_auto_20250331_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordrevirement',
            name='compte_tresorerie_emetteur',
            field=models.ForeignKey(blank=True, limit_choices_to={'actif': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordres_virements_emetteur', to='fournisseurs.comptetresorerie', verbose_name='Compte bancaire émetteur'),
        ),
    ]
