# Generated by Django 3.2.25 on 2025-04-04 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0035_alter_ordrevirement_compte_tresorerie_emetteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptetresorerie',
            name='est_nantissement',
            field=models.BooleanField(default=False, help_text='Cochez si ce compte est utilisé pour un nantissement (peut partager le RIB)', verbose_name='Compte en nantissement'),
        ),
        migrations.AlterField(
            model_name='comptetresorerie',
            name='rib',
            field=models.CharField(blank=True, error_messages={'unique': 'Ce RIB est déjà utilisé.'}, help_text='Numéro du compte bancaire (uniquement pour les comptes bancaires)', max_length=24, null=True, validators=[django.core.validators.RegexValidator(message='Le RIB doit contenir exactement 24 chiffres.', regex='^\\d{24}$')], verbose_name='RIB'),
        ),
        migrations.AddConstraint(
            model_name='comptetresorerie',
            constraint=models.UniqueConstraint(condition=models.Q(('est_nantissement', False)), fields=('rib',), name='rib_unique_sauf_nantissement'),
        ),
    ]
