# Generated by Django 3.2.25 on 2025-04-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0036_auto_20250404_1423'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comptetresorerie',
            name='rib_unique_sauf_nantissement',
        ),
    ]
