# Generated by Django 3.2.25 on 2025-04-14 11:15

from django.db import migrations, models
import django.db.models.deletion
import stages.models
import stages.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=15, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('cin', models.CharField(max_length=10, unique=True)),
                ('dateN', models.DateField()),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.TextField()),
                ('niveau', models.CharField(max_length=30)),
                ('ecole', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to=stages.models.rename_upload_path_cv, validators=[stages.validators.validate_file_extension])),
                ('lettre', models.FileField(upload_to=stages.models.rename_upload_path_lettre, validators=[stages.validators.validate_file_extension])),
                ('isChecked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('selectedPeriode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='stages.periode')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville_origine', to='stages.ville')),
                ('villeEcole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville_ecole', to='stages.ville')),
            ],
            options={
                'permissions': [('can_download', 'Can download stage data')],
            },
        ),
    ]
