# Generated by Django 3.2.25 on 2024-05-08 07:50

from django.db import migrations, models
import django.db.models.deletion
import stages.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('cin', models.CharField(max_length=10)),
                ('dateN', models.DateField()),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.TextField()),
                ('niveau', models.CharField(max_length=30)),
                ('ecole', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=20)),
                ('cv', models.FileField(default=None, upload_to='uploads/', validators=[stages.validators.validate_file_extension])),
                ('lettre', models.FileField(default=None, upload_to='uploads/', validators=[stages.validators.validate_file_extension])),
                ('conditions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectedPeriode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.periode')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville_origine', to='stages.ville')),
                ('villeEcole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville_ecole', to='stages.ville')),
            ],
        ),
    ]
