# Generated by Django 3.2.25 on 2025-05-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='encore_scolarise',
            field=models.BooleanField(default=False),
        ),
    ]
