# Generated by Django 3.2.25 on 2024-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='cin',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
