# Generated by Django 3.2.25 on 2025-05-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_stage_encore_scolarise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='encore_scolarise',
            field=models.BooleanField(default=False, help_text="Cochez cette case si vous êtes actuellement inscrit dans un établissement d'enseignement", verbose_name='Êtes-vous encore scolarisé(e) ?'),
        ),
    ]
