# Generated by Django 3.2.25 on 2024-05-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_stage_cin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='conditions',
            new_name='isChecked',
        ),
    ]
