# Generated by Django 3.2.25 on 2025-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_alter_stage_encore_scolarise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='ville',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
