# Generated by Django 3.2.25 on 2024-05-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_rename_conditions_stage_ischecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='specialite',
            field=models.CharField(max_length=50),
        ),
    ]
