# Generated by Django 3.2.25 on 2024-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_stage_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='traite',
            field=models.BooleanField(default=False),
        ),
    ]
