# Generated by Django 3.2.25 on 2024-06-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_alter_stage_selectedperiode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'permissions': [('can_download', 'Can download stage data')]},
        ),
        migrations.AddField(
            model_name='stage',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
