# Generated by Django 3.2.25 on 2024-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_auto_20240602_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
