# Generated by Django 3.2.25 on 2024-06-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_auto_20240604_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='custom_message',
        ),
    ]
