# Generated by Django 3.2.25 on 2024-06-08 17:40

from django.db import migrations, models
import stages.models
import stages.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0010_remove_stage_custom_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='cv',
            field=models.FileField(default=None, upload_to=stages.models.rename_upload_path_cv, validators=[stages.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='stage',
            name='lettre',
            field=models.FileField(default=None, upload_to=stages.models.rename_upload_path_lettre, validators=[stages.validators.validate_file_extension]),
        ),
    ]
