# Generated by Django 3.2.25 on 2025-02-12 20:57

from django.db import migrations, models
import omra.models
import omra.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Omra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=15, unique=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to=omra.models.rename_upload_path_omra, validators=[omra.validators.validate_file_extension])),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_download', 'Can download omra data')],
            },
        ),
    ]
